# Generated by Django 3.2.8 on 2021-10-29 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jukebox', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='click',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
